### PR TITLE
change subdomain from "cdn" to "get"

### PR DESCRIPTION
**Pull request by AlJohri**

### CODE REVIEW

**Comment by casidiablo** [comment]
Why?

See there's people in other countries that when using `get`, can't download the cask. Are you also experiencing problems?

**Comment by AlJohri** [comment]
I am, unfortunately. I'm in the US Greater New York Area.

```
➜  ~  curl -i https://cdn.popcorntime.io/build/Popcorn-Time-0.3.7.2-Mac.dmg
HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 27 Jun 2015 18:17:59 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

```
➜  ~  curl -i https://get.popcorntime.io/build/Popcorn-Time-0.3.7.2-Mac.dmg
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Sat, 27 Jun 2015 18:18:48 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.5
Location: http://104.131.61.151/build/Popcorn-Time-0.3.7.2-Mac.dmg
Expires: Sat, 27 Jun 2015 18:19:48 GMT
Cache-Control: max-age=60
```

**Comment by casidiablo** [comment]
Well, that sucks. I don't think caskroom has a way to specify multiple mirror URLs.

I could host this my self, but then I'm pretty sure I will receive complaints from people distrusting the download. Aguably as long as the SHA-1 is the same they shouldn't, but there's many paranoid people out there (me included).

**Comment by AlJohri** [comment]
I'm curious, where does `curl -i` point to for the cdn url?

**Comment by casidiablo** [comment]
From the east coast, if I try to use the cdn one I get this:

```
Server: nginx
Date: Sat, 27 Jun 2015 22:45:54 GMT
Content-Type: application/octet-stream
Content-Length: 38147354
Last-Modified: Mon, 16 Feb 2015 13:31:28 GMT
Connection: keep-alive
ETag: "54e1f130-246151a"
Expires: Sun, 28 Jun 2015 22:45:54 GMT
Cache-Control: max-age=86400
Strict-Transport-Security: max-age=15638400
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
```

No redirects or anything.

**Pull request closed without merging**
